server:
  port: 8006

spring:
  application:
    name: cloud-provider-payment
  #数据源
  datasource:
    #当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #mysql驱动包
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  type-aliases-package: com.ncu.springcloud.entity
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7004.com:7004/eureka
  instance:
    instance-id: payment8006
    prefer-ip-address: true